backend:
  name: github
  repo: Hydrowind/splash

media_folder: static/assets
public_folder: assets

collections:
  - name: "post"
    label: "Posts"
    folder: "contents"
    create: true
    slug: "{{month}}-{{day}}-{{year}}-{{slug}}"
    fields:
      - { name: path, label: Path, widget: string }
      - { name: author, label: Author, widget: string, default: Herdhiantoko Fathani }
      - { name: date, label: Date, widget: date, format: DD-MM-YYYY }
      - { name: title, label: Title, widget: string }
      - { name: cover, label: Cover, widget: image }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown }